### ISSUE TITLE
File/Directory not found

### ISSUE THREAD

**Issue by Sukarett2** [tuurep/windowlist#1]
Ran **windowlist** and was returned with

`/home/sukaretto/.config/polybar/waa/scripts/windowlist/windowlist.sh: line 142: /home/sukaretto/.config/polybar/waa/scripts/windowlist/list_windows: No such file or directory`

![image](https://user-images.githubusercontent.com/70230904/179054195-d3083932-0fae-4f8d-a488-7f75a5dbebb8.png)

Don't know if this is a me issue.

**Comment by Sukarett2** [comment]
nvm was being stupid

**Comment by tuurep** [comment]
Oh :D

Hopefully it worked? I'm curious whether the makefile works on distributions other than Arch Linux.

I derived it from the `wmctrl` source code by running the configure script and then making it as bare-minimum as I possibly could, so that I could just start modifying the one function that lists the window properties when you run `wmctrl -lx` (and similar flags).
